Tensor Flow Intro

Tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents Tensors as dimensional arrays of base datatypes.
Tensors store partially defined computations in a graph.

Each tensor ahs a data type and a shape

Datatypes: float32,int32,string,others

Shape: Dimension of data

In [ ]:
import tensorflow as tf

In [ ]:
rank1_tensor=tf.Variable(["Test","Okay","Tim"],tf.string)
rank2_tensor=tf.Variable([["test","ok"],["test","yes"],["nigga","lol"]],tf.string)



Rank determination

In [ ]:
tf.rank(rank2_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
rank2_tensor.shape

TensorShape([3, 2])

In [ ]:
rank1_tensor.shape

TensorShape([3])

***Changing the shape of the tensor***

In [ ]:
tensor1=tf.ones([1,2,3])
tensor2=tf.reshape(tensor1,[2,3,1])
tensor3=tf.reshape(tensor2,[3,-1])
#

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


**TYPES OF TENSOR**


1.   Variable
2.   Constant
3.  Placeholder
4. SparseTensor

